main: ${project.groupId}.${project.name}
name: ${project.name}
version: ${project.version}
website: ${project.url}
description: ${project.description}
authors: [Cayorion]
depend: [MassiveCore]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  wess.wess: {description: WE-save with name from sign, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  wess.*:
    default: false
    children:
      wess.wess: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  wess.kit.operator:
    default: op
    children:
      wess.*: true
  wess.kit.rank3:
    default: false
    children:
      wess.kit.rank2: true
  wess.kit.rank2:
    default: false
    children:
      wess.kit.rank1: true
  wess.kit.rank1:
    default: false
    children:
      wess.kit.rank0: true
      wess.wess: true
  wess.kit.rank0:
    default: false
    children:
  wess.kit.default:
    default: true
    children:
      wess.kit.rank0: true
